//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangfire.Dashboard.Content.resx.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t worry, continuations are working as expected. But your current job storage does not support some queries required to show this page. Please try to update your storage or wait until the full command set is implemented. 的本地化字符串。
        /// </summary>
        public static string AwaitingJobsPage_ContinuationsWarning_Text {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_ContinuationsWarning_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continuations are working, but this page can&apos;t be displayed 的本地化字符串。
        /// </summary>
        public static string AwaitingJobsPage_ContinuationsWarning_Title {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_ContinuationsWarning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No jobs found in awaiting state. 的本地化字符串。
        /// </summary>
        public static string AwaitingJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        public static string AwaitingJobsPage_Table_Options {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_Table_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent 的本地化字符串。
        /// </summary>
        public static string AwaitingJobsPage_Table_Parent {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_Table_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting Jobs 的本地化字符串。
        /// </summary>
        public static string AwaitingJobsPage_Title {
            get {
                return ResourceManager.GetString("AwaitingJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find the target method. 的本地化字符串。
        /// </summary>
        public static string Common_CannotFindTargetMethod {
            get {
                return ResourceManager.GetString("Common_CannotFindTargetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condition 的本地化字符串。
        /// </summary>
        public static string Common_Condition {
            get {
                return ResourceManager.GetString("Common_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continuations 的本地化字符串。
        /// </summary>
        public static string Common_Continuations {
            get {
                return ResourceManager.GetString("Common_Continuations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created 的本地化字符串。
        /// </summary>
        public static string Common_Created {
            get {
                return ResourceManager.GetString("Common_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to DELETE ALL selected jobs? 的本地化字符串。
        /// </summary>
        public static string Common_DeleteConfirm {
            get {
                return ResourceManager.GetString("Common_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete selected 的本地化字符串。
        /// </summary>
        public static string Common_DeleteSelected {
            get {
                return ResourceManager.GetString("Common_DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleting... 的本地化字符串。
        /// </summary>
        public static string Common_Deleting {
            get {
                return ResourceManager.GetString("Common_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueue jobs 的本地化字符串。
        /// </summary>
        public static string Common_EnqueueButton_Text {
            get {
                return ResourceManager.GetString("Common_EnqueueButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued 的本地化字符串。
        /// </summary>
        public static string Common_Enqueued {
            get {
                return ResourceManager.GetString("Common_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueueing... 的本地化字符串。
        /// </summary>
        public static string Common_Enqueueing {
            get {
                return ResourceManager.GetString("Common_Enqueueing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetched 的本地化字符串。
        /// </summary>
        public static string Common_Fetched {
            get {
                return ResourceManager.GetString("Common_Fetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        public static string Common_Id {
            get {
                return ResourceManager.GetString("Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job 的本地化字符串。
        /// </summary>
        public static string Common_Job {
            get {
                return ResourceManager.GetString("Common_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job expired. 的本地化字符串。
        /// </summary>
        public static string Common_JobExpired {
            get {
                return ResourceManager.GetString("Common_JobExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job&apos;s state has been changed while fetching data. 的本地化字符串。
        /// </summary>
        public static string Common_JobStateChanged_Text {
            get {
                return ResourceManager.GetString("Common_JobStateChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Less details... 的本地化字符串。
        /// </summary>
        public static string Common_LessDetails {
            get {
                return ResourceManager.GetString("Common_LessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More details... 的本地化字符串。
        /// </summary>
        public static string Common_MoreDetails {
            get {
                return ResourceManager.GetString("Common_MoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No state 的本地化字符串。
        /// </summary>
        public static string Common_NoState {
            get {
                return ResourceManager.GetString("Common_NoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        public static string Common_NotAvailable {
            get {
                return ResourceManager.GetString("Common_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Day 的本地化字符串。
        /// </summary>
        public static string Common_PeriodDay {
            get {
                return ResourceManager.GetString("Common_PeriodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Week 的本地化字符串。
        /// </summary>
        public static string Common_PeriodWeek {
            get {
                return ResourceManager.GetString("Common_PeriodWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reason 的本地化字符串。
        /// </summary>
        public static string Common_Reason {
            get {
                return ResourceManager.GetString("Common_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requeue jobs 的本地化字符串。
        /// </summary>
        public static string Common_RequeueJobs {
            get {
                return ResourceManager.GetString("Common_RequeueJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retry 的本地化字符串。
        /// </summary>
        public static string Common_Retry {
            get {
                return ResourceManager.GetString("Common_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server 的本地化字符串。
        /// </summary>
        public static string Common_Server {
            get {
                return ResourceManager.GetString("Common_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string Common_State {
            get {
                return ResourceManager.GetString("Common_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        public static string Common_Unknown {
            get {
                return ResourceManager.GetString("Common_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No deleted jobs found. 的本地化字符串。
        /// </summary>
        public static string DeletedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("DeletedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted 的本地化字符串。
        /// </summary>
        public static string DeletedJobsPage_Table_Deleted {
            get {
                return ResourceManager.GetString("DeletedJobsPage_Table_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted Jobs 的本地化字符串。
        /// </summary>
        public static string DeletedJobsPage_Title {
            get {
                return ResourceManager.GetString("DeletedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The queue is empty. 的本地化字符串。
        /// </summary>
        public static string EnqueuedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("EnqueuedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued jobs 的本地化字符串。
        /// </summary>
        public static string EnqueuedJobsPage_Title {
            get {
                return ResourceManager.GetString("EnqueuedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;strong&gt;Failed jobs do not become expired&lt;/strong&gt; to allow you to re-queue them without any
        ///                time pressure. You should re-queue or delete them manually, or apply &lt;code&gt;AutomaticRetry(OnAttemptsExceeded = AttemptsExceededAction.Delete)&lt;/code&gt;
        ///                attribute to delete them automatically. 的本地化字符串。
        /// </summary>
        public static string FailedJobsPage_FailedJobsNotExpire_Warning_Html {
            get {
                return ResourceManager.GetString("FailedJobsPage_FailedJobsNotExpire_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have no failed jobs at the moment. 的本地化字符串。
        /// </summary>
        public static string FailedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("FailedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string FailedJobsPage_Table_Failed {
            get {
                return ResourceManager.GetString("FailedJobsPage_Table_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed Jobs 的本地化字符串。
        /// </summary>
        public static string FailedJobsPage_Title {
            get {
                return ResourceManager.GetString("FailedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The queue is empty. 的本地化字符串。
        /// </summary>
        public static string FetchedJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("FetchedJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fetched jobs 的本地化字符串。
        /// </summary>
        public static string FetchedJobsPage_Title {
            get {
                return ResourceManager.GetString("FetchedJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string HomePage_GraphHover_Failed {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded 的本地化字符串。
        /// </summary>
        public static string HomePage_GraphHover_Succeeded {
            get {
                return ResourceManager.GetString("HomePage_GraphHover_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History graph 的本地化字符串。
        /// </summary>
        public static string HomePage_HistoryGraph {
            get {
                return ResourceManager.GetString("HomePage_HistoryGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realtime graph 的本地化字符串。
        /// </summary>
        public static string HomePage_RealtimeGraph {
            get {
                return ResourceManager.GetString("HomePage_RealtimeGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        public static string HomePage_Title {
            get {
                return ResourceManager.GetString("HomePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_Created {
            get {
                return ResourceManager.GetString("JobDetailsPage_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete this job? 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_DeleteConfirm {
            get {
                return ResourceManager.GetString("JobDetailsPage_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;strong&gt;The job was aborted&lt;/strong&gt; – it is processed by server
        ///                        &lt;code&gt;{0}&lt;/code&gt; which is not in the 
        ///                        &lt;a href=&quot;{1}&quot;&gt;active servers&lt;/a&gt; list for now.
        ///                        It will be retried automatically after invisibility timeout, but you can
        ///                        also re-queue or delete it manually. 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_JobAbortedNotActive_Warning_Html {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobAbortedNotActive_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;strong&gt;Looks like the job was aborted&lt;/strong&gt; – it is processed by server
        ///                        &lt;code&gt;{0}&lt;/code&gt;, which reported its heartbeat more than 1 minute ago.
        ///                        It will be retried automatically after invisibility timeout, but you can
        ///                        also re-queue or delete it manually. 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_JobAbortedWithHeartbeat_Warning_Html {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobAbortedWithHeartbeat_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background job &apos;{0}&apos; has expired or could not be found on the server. 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_JobExpired {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;strong&gt;The job is finished&lt;/strong&gt;.
        ///                    It will be removed automatically &lt;em&gt;&lt;abbr data-moment=&quot;{0}&quot;&gt;{1}&lt;/abbr&gt;&lt;/em&gt;. 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_JobFinished_Warning_Html {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobFinished_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job ID 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_JobId {
            get {
                return ResourceManager.GetString("JobDetailsPage_JobId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requeue 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_Requeue {
            get {
                return ResourceManager.GetString("JobDetailsPage_Requeue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string JobDetailsPage_State {
            get {
                return ResourceManager.GetString("JobDetailsPage_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting 的本地化字符串。
        /// </summary>
        public static string JobsSidebarMenu_Awaiting {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Awaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted 的本地化字符串。
        /// </summary>
        public static string JobsSidebarMenu_Deleted {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued 的本地化字符串。
        /// </summary>
        public static string JobsSidebarMenu_Enqueued {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Enqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string JobsSidebarMenu_Failed {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        public static string JobsSidebarMenu_Processing {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled 的本地化字符串。
        /// </summary>
        public static string JobsSidebarMenu_Scheduled {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded 的本地化字符串。
        /// </summary>
        public static string JobsSidebarMenu_Succeeded {
            get {
                return ResourceManager.GetString("JobsSidebarMenu_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back to site 的本地化字符串。
        /// </summary>
        public static string LayoutPage_Back {
            get {
                return ResourceManager.GetString("LayoutPage_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generated: {0}ms 的本地化字符串。
        /// </summary>
        public static string LayoutPage_Footer_Generatedms {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Generatedms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time: 的本地化字符串。
        /// </summary>
        public static string LayoutPage_Footer_Time {
            get {
                return ResourceManager.GetString("LayoutPage_Footer_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Connections 的本地化字符串。
        /// </summary>
        public static string Metrics_ActiveConnections {
            get {
                return ResourceManager.GetString("Metrics_ActiveConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Awaiting 的本地化字符串。
        /// </summary>
        public static string Metrics_AwaitingCount {
            get {
                return ResourceManager.GetString("Metrics_AwaitingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted Jobs 的本地化字符串。
        /// </summary>
        public static string Metrics_DeletedJobs {
            get {
                return ResourceManager.GetString("Metrics_DeletedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued 的本地化字符串。
        /// </summary>
        public static string Metrics_EnqueuedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueued / Queues 的本地化字符串。
        /// </summary>
        public static string Metrics_EnqueuedQueuesCount {
            get {
                return ResourceManager.GetString("Metrics_EnqueuedQueuesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} failed job(s) found. Retry or delete them manually. 的本地化字符串。
        /// </summary>
        public static string Metrics_FailedCountOrNull {
            get {
                return ResourceManager.GetString("Metrics_FailedCountOrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed Jobs 的本地化字符串。
        /// </summary>
        public static string Metrics_FailedJobs {
            get {
                return ResourceManager.GetString("Metrics_FailedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing Jobs 的本地化字符串。
        /// </summary>
        public static string Metrics_ProcessingJobs {
            get {
                return ResourceManager.GetString("Metrics_ProcessingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurring Jobs 的本地化字符串。
        /// </summary>
        public static string Metrics_RecurringJobs {
            get {
                return ResourceManager.GetString("Metrics_RecurringJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retries 的本地化字符串。
        /// </summary>
        public static string Metrics_Retries {
            get {
                return ResourceManager.GetString("Metrics_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled Jobs 的本地化字符串。
        /// </summary>
        public static string Metrics_ScheduledJobs {
            get {
                return ResourceManager.GetString("Metrics_ScheduledJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servers 的本地化字符串。
        /// </summary>
        public static string Metrics_Servers {
            get {
                return ResourceManager.GetString("Metrics_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded Jobs 的本地化字符串。
        /// </summary>
        public static string Metrics_SucceededJobs {
            get {
                return ResourceManager.GetString("Metrics_SucceededJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Connections 的本地化字符串。
        /// </summary>
        public static string Metrics_TotalConnections {
            get {
                return ResourceManager.GetString("Metrics_TotalConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jobs 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Jobs {
            get {
                return ResourceManager.GetString("NavigationMenu_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurring Jobs 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_RecurringJobs {
            get {
                return ResourceManager.GetString("NavigationMenu_RecurringJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retries 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Retries {
            get {
                return ResourceManager.GetString("NavigationMenu_Retries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servers 的本地化字符串。
        /// </summary>
        public static string NavigationMenu_Servers {
            get {
                return ResourceManager.GetString("NavigationMenu_Servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Paginator_Next {
            get {
                return ResourceManager.GetString("Paginator_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev 的本地化字符串。
        /// </summary>
        public static string Paginator_Prev {
            get {
                return ResourceManager.GetString("Paginator_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total items 的本地化字符串。
        /// </summary>
        public static string Paginator_TotalItems {
            get {
                return ResourceManager.GetString("Paginator_TotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Items per page 的本地化字符串。
        /// </summary>
        public static string PerPageSelector_ItemsPerPage {
            get {
                return ResourceManager.GetString("PerPageSelector_ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looks like the job was aborted 的本地化字符串。
        /// </summary>
        public static string ProcessingJobsPage_Aborted {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No jobs are being processed right now. 的本地化字符串。
        /// </summary>
        public static string ProcessingJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started 的本地化字符串。
        /// </summary>
        public static string ProcessingJobsPage_Table_Started {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Table_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing Jobs 的本地化字符串。
        /// </summary>
        public static string ProcessingJobsPage_Title {
            get {
                return ResourceManager.GetString("ProcessingJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No jobs queued. 的本地化字符串。
        /// </summary>
        public static string QueuesPage_NoJobs {
            get {
                return ResourceManager.GetString("QueuesPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No queued jobs found. Try to enqueue a job. 的本地化字符串。
        /// </summary>
        public static string QueuesPage_NoQueues {
            get {
                return ResourceManager.GetString("QueuesPage_NoQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length 的本地化字符串。
        /// </summary>
        public static string QueuesPage_Table_Length {
            get {
                return ResourceManager.GetString("QueuesPage_Table_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next jobs 的本地化字符串。
        /// </summary>
        public static string QueuesPage_Table_NextsJobs {
            get {
                return ResourceManager.GetString("QueuesPage_Table_NextsJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queue 的本地化字符串。
        /// </summary>
        public static string QueuesPage_Table_Queue {
            get {
                return ResourceManager.GetString("QueuesPage_Table_Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queues 的本地化字符串。
        /// </summary>
        public static string QueuesPage_Title {
            get {
                return ResourceManager.GetString("QueuesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceled 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_Canceled {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No recurring jobs found. 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("RecurringJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cron 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_Table_Cron {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_Cron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last execution 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_Table_LastExecution {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_LastExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next execution 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_Table_NextExecution {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_NextExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time zone 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_Table_TimeZone {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Table_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recurring jobs 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_Title {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triggering... 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_Triggering {
            get {
                return ResourceManager.GetString("RecurringJobsPage_Triggering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trigger now 的本地化字符串。
        /// </summary>
        public static string RecurringJobsPage_TriggerNow {
            get {
                return ResourceManager.GetString("RecurringJobsPage_TriggerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All is OK – you have no retries. 的本地化字符串。
        /// </summary>
        public static string RetriesPage_NoJobs {
            get {
                return ResourceManager.GetString("RetriesPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retries 的本地化字符串。
        /// </summary>
        public static string RetriesPage_Title {
            get {
                return ResourceManager.GetString("RetriesPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;h4&gt;Retries are working, but this page can&apos;t be displayed&lt;/h4&gt;
        ///        &lt;p&gt;
        ///            Don&apos;t worry, retries are working as expected. Your current job storage does not support
        ///            some queries required to show this page. Please try to update your storage or wait until
        ///            the full command set is implemented.
        ///        &lt;/p&gt;
        ///        &lt;p&gt;
        ///            Please go to the &lt;a href=&quot;{0}&quot;&gt;Scheduled jobs&lt;/a&gt; page to see all the
        ///            scheduled jobs including retries.
        ///        &lt;/p&gt; 的本地化字符串。
        /// </summary>
        public static string RetriesPage_Warning_Html {
            get {
                return ResourceManager.GetString("RetriesPage_Warning_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueue now 的本地化字符串。
        /// </summary>
        public static string ScheduledJobsPage_EnqueueNow {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_EnqueueNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no scheduled jobs. 的本地化字符串。
        /// </summary>
        public static string ScheduledJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enqueue 的本地化字符串。
        /// </summary>
        public static string ScheduledJobsPage_Table_Enqueue {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_Table_Enqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled 的本地化字符串。
        /// </summary>
        public static string ScheduledJobsPage_Table_Scheduled {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_Table_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scheduled Jobs 的本地化字符串。
        /// </summary>
        public static string ScheduledJobsPage_Title {
            get {
                return ResourceManager.GetString("ScheduledJobsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no active servers. Background tasks will not be processed. 的本地化字符串。
        /// </summary>
        public static string ServersPage_NoServers {
            get {
                return ResourceManager.GetString("ServersPage_NoServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heartbeat 的本地化字符串。
        /// </summary>
        public static string ServersPage_Table_Heartbeat {
            get {
                return ResourceManager.GetString("ServersPage_Table_Heartbeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string ServersPage_Table_Name {
            get {
                return ResourceManager.GetString("ServersPage_Table_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Queues 的本地化字符串。
        /// </summary>
        public static string ServersPage_Table_Queues {
            get {
                return ResourceManager.GetString("ServersPage_Table_Queues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Started 的本地化字符串。
        /// </summary>
        public static string ServersPage_Table_Started {
            get {
                return ResourceManager.GetString("ServersPage_Table_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workers 的本地化字符串。
        /// </summary>
        public static string ServersPage_Table_Workers {
            get {
                return ResourceManager.GetString("ServersPage_Table_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Servers 的本地化字符串。
        /// </summary>
        public static string ServersPage_Title {
            get {
                return ResourceManager.GetString("ServersPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No succeeded jobs found. 的本地化字符串。
        /// </summary>
        public static string SucceededJobsPage_NoJobs {
            get {
                return ResourceManager.GetString("SucceededJobsPage_NoJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded 的本地化字符串。
        /// </summary>
        public static string SucceededJobsPage_Table_Succeeded {
            get {
                return ResourceManager.GetString("SucceededJobsPage_Table_Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total Duration 的本地化字符串。
        /// </summary>
        public static string SucceededJobsPage_Table_TotalDuration {
            get {
                return ResourceManager.GetString("SucceededJobsPage_Table_TotalDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded Jobs 的本地化字符串。
        /// </summary>
        public static string SucceededJobsPage_Title {
            get {
                return ResourceManager.GetString("SucceededJobsPage_Title", resourceCulture);
            }
        }
    }
}
